services:
  - type: web
    name: prestige-auto-spa
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*.html
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
